In [7]:
import pandas as pd 
import sql

ModuleNotFoundError: No module named 'sql'

In [4]:
df = pd.read_csv(r'/Users/venkatasaikumargundu/Desktop/FullStack Datascience and AI /Datasets/dataset_1_202602121653.csv')
df.head()

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5

In [5]:
df.shape

(12684, 27)

In [8]:
df[['weather', 'temperature']]

      weather  temperature
0       Sunny           55
1       Sunny           80
2       Sunny           80
3       Sunny           80
4       Sunny           80
...       ...          ...
12679   Rainy           55
12680   Rainy           55
12681   Snowy           30
12682   Snowy           30
12683   Sunny           80

[12684 rows x 2 columns]

In [10]:
df.head(11)

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
5,No Urgent Place,Friend(s),Sunny,80,6PM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,6
6,No Urgent Place,Friend(s),Sunny,55,2PM,Carry out & Take away,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,7
7,No Urgent Place,Kid(s),Sunny,80,10AM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,8
8,No Urgent Place,Kid(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,9
9,No Urgent Place,Kid(s),Sunny,80,10AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,10
10,No Urgent Place,Kid(s),Sunny,80,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,11

In [12]:
df[:11]

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
5,No Urgent Place,Friend(s),Sunny,80,6PM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,6
6,No Urgent Place,Friend(s),Sunny,55,2PM,Carry out & Take away,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,7
7,No Urgent Place,Kid(s),Sunny,80,10AM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,8
8,No Urgent Place,Kid(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,9
9,No Urgent Place,Kid(s),Sunny,80,10AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,10
10,No Urgent Place,Kid(s),Sunny,80,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,11

In [13]:
df['passanger'].unique()

array(['Alone', 'Friend(s)', 'Kid(s)', 'Partner'], dtype=object)

In [14]:
df['passanger'].nunique()

4

In [21]:
df["destination"].unique()

array(['No Urgent Place', 'Home', 'Work'], dtype=object)

In [22]:
df[df["destination"].str.contains("Home")]

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
13,Home,Alone,Sunny,55,6PM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,1,0,1,14
14,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,15
15,Home,Alone,Sunny,80,6PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,16
35,Home,Alone,Sunny,55,6PM,Bar,1d,Male,21,Single,...,4~8,4~8,less1,1,0,0,1,0,1,36
36,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Male,21,Single,...,4~8,4~8,less1,1,1,0,0,1,0,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12675,Home,Alone,Snowy,30,10PM,Coffee House,2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,0,1,0,12676
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680

In [25]:
df.sort_values(by="coupon", ascending=True)

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
11702,Home,Partner,Sunny,30,10PM,Bar,2h,Female,50plus,Married partner,...,4~8,1~3,less1,1,1,1,0,1,0,11703
9930,No Urgent Place,Alone,Snowy,30,2PM,Bar,1d,Female,21,Single,...,gt8,gt8,4~8,1,0,0,0,1,0,9931
10632,Home,Alone,Rainy,55,6PM,Bar,1d,Male,21,Single,...,gt8,less1,less1,1,1,1,0,1,0,10633
7997,No Urgent Place,Friend(s),Rainy,55,10PM,Bar,2h,Male,26,Unmarried partner,...,4~8,never,1~3,1,1,0,0,1,1,7998
11166,Work,Alone,Snowy,30,7AM,Bar,1d,Female,41,Married partner,...,gt8,1~3,less1,1,1,1,0,1,0,11167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,Home,Alone,Sunny,80,6PM,Restaurant(<20),1d,Female,31,Unmarried partner,...,1~3,1~3,less1,1,0,0,1,0,1,10477
5447,Home,Alone,Sunny,80,10PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,0,0,1,0,0,5448
10478,Home,Alone,Snowy,30,10PM,Restaurant(<20),2h,Female,31,Unmarried partner,...,1~3,1~3,less1,1,1,1,0,1,0,10479
5440,No Urgent Place,Alone,Sunny,80,2PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,1,0,0,1,0,5441
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1

In [28]:
df[['destination']].rename(columns={'destination':'Destination'})

           Destination
0      No Urgent Place
1      No Urgent Place
2      No Urgent Place
3      No Urgent Place
4      No Urgent Place
...                ...
12679             Home
12680             Work
12681             Work
12682             Work
12683             Work

[12684 rows x 1 columns]

In [ ]:
df.groupby('occupation') # groupby() does nothing visually. You must atleast apply size(), count(), sum(), mean(), agg()
# sum() --- counts all rows and also includes missing values. 
# count() --- counts only non-null values in each column. 
#

In [32]:
df.groupby('occupation').size().reset_index()[['occupation']]

                                   occupation
0                  Architecture & Engineering
1    Arts Design Entertainment Sports & Media
2   Building & Grounds Cleaning & Maintenance
3                        Business & Financial
4                 Community & Social Services
5                     Computer & Mathematical
6                   Construction & Extraction
7                  Education&Training&Library
8                  Farming Fishing & Forestry
9          Food Preparation & Serving Related
10       Healthcare Practitioners & Technical
11                         Healthcare Support
12          Installation Maintenance & Repair
13                                      Legal
14               Life Physical Social Science
15                                 Management
16            Office & Administrative Support
17                    Personal Care & Service
18                     Production Occupations
19                         Protective Service
20                                    Retired
21                            Sales & Related
22                                    Student
23           Transportation & Material Moving
24                                 Unemployed

In [33]:
df[['occupation']].drop_duplicates()

                                     occupation
0                                    Unemployed
22                   Architecture & Engineering
44                                      Student
66                   Education&Training&Library
154                          Healthcare Support
176        Healthcare Practitioners & Technical
193                             Sales & Related
215                                  Management
281    Arts Design Entertainment Sports & Media
343                     Computer & Mathematical
365                Life Physical Social Science
409                     Personal Care & Service
495                 Community & Social Services
589             Office & Administrative Support
655                   Construction & Extraction
765                                       Legal
830                                     Retired
1831          Installation Maintenance & Repair
1919           Transportation & Material Moving
2139                       Business & Financial
2205                         Protective Service
3004         Food Preparation & Serving Related
4940                     Production Occupations
7063  Building & Grounds Cleaning & Maintenance
8430                 Farming Fishing & Forestry

In [34]:
df[['occupation']].drop_duplicates().sort_values('occupation')

                                     occupation
22                   Architecture & Engineering
281    Arts Design Entertainment Sports & Media
7063  Building & Grounds Cleaning & Maintenance
2139                       Business & Financial
495                 Community & Social Services
343                     Computer & Mathematical
655                   Construction & Extraction
66                   Education&Training&Library
8430                 Farming Fishing & Forestry
3004         Food Preparation & Serving Related
176        Healthcare Practitioners & Technical
154                          Healthcare Support
1831          Installation Maintenance & Repair
765                                       Legal
365                Life Physical Social Science
215                                  Management
589             Office & Administrative Support
409                     Personal Care & Service
4940                     Production Occupations
2205                         Protective Service
830                                     Retired
193                             Sales & Related
44                                      Student
1919           Transportation & Material Moving
0                                    Unemployed

In [35]:
df['occupation'].unique()

array(['Unemployed', 'Architecture & Engineering', 'Student',
       'Education&Training&Library', 'Healthcare Support',
       'Healthcare Practitioners & Technical', 'Sales & Related',
       'Management', 'Arts Design Entertainment Sports & Media',
       'Computer & Mathematical', 'Life Physical Social Science',
       'Personal Care & Service', 'Community & Social Services',
       'Office & Administrative Support', 'Construction & Extraction',
       'Legal', 'Retired', 'Installation Maintenance & Repair',
       'Transportation & Material Moving', 'Business & Financial',
       'Protective Service', 'Food Preparation & Serving Related',
       'Production Occupations',
       'Building & Grounds Cleaning & Maintenance',
       'Farming Fishing & Forestry'], dtype=object)

In [39]:
df[['weather','temperature']].groupby('temperature').mean('temperature')

Empty DataFrame
Columns: []
Index: [30, 55, 80]

In [40]:
df.groupby('weather', as_index=False).agg(avg_temp = ('temperature', 'mean'))

  weather   avg_temp
0   Rainy  55.000000
1   Snowy  30.000000
2   Sunny  68.946271

In [41]:
df.groupby('weather')['temperature'].mean().reset_index(name='avg_temp')

  weather   avg_temp
0   Rainy  55.000000
1   Snowy  30.000000
2   Sunny  68.946271

In [45]:
df.groupby('weather', as_index=False).agg(count = ('temperature', 'count'))

  weather  count
0   Rainy   1210
1   Snowy   1405
2   Sunny  10069

In [46]:
df.groupby('weather')['temperature'].count().reset_index(name = 'count')

  weather  count
0   Rainy   1210
1   Snowy   1405
2   Sunny  10069

In [51]:
df.groupby('weather',as_index=False).agg(count = ('temperature','nunique'))

  weather  count
0   Rainy      1
1   Snowy      1
2   Sunny      3

In [54]:
df.groupby('weather',as_index=False).agg(count = ('temperature','unique'))

  weather         count
0   Rainy          [55]
1   Snowy          [30]
2   Sunny  [55, 80, 30]

In [55]:
df.groupby('weather')['temperature'].sum().reset_index(name = 'sum')

  weather     sum
0   Rainy   66550
1   Snowy   42150
2   Sunny  694220

In [56]:
df.groupby('weather',as_index=False).agg(sum_temp = ('temperature', 'sum'))

  weather  sum_temp
0   Rainy     66550
1   Snowy     42150
2   Sunny    694220

In [57]:
df.groupby('weather',as_index=False).agg(min_temp = ('temperature', 'min'))

  weather  min_temp
0   Rainy        55
1   Snowy        30
2   Sunny        30

In [58]:
df.groupby('weather')['temperature'].min().reset_index(name = 'min_temp')

  weather  min_temp
0   Rainy        55
1   Snowy        30
2   Sunny        30

In [59]:
df.groupby('weather',as_index=False).agg(max_temp = ('temperature', 'max'))

  weather  max_temp
0   Rainy        55
1   Snowy        30
2   Sunny        80

In [60]:
df.groupby('weather')['temperature'].min().reset_index(name = 'max_temp')

  weather  max_temp
0   Rainy        55
1   Snowy        30
2   Sunny        30

In [70]:
df[['occupation']].drop_duplicates().query("occupation == 'Student'")

   occupation
44    Student

In [71]:
df.loc[df['occupation'] == 'Student', ['occupation']].drop_duplicates()

   occupation
44    Student

# **JOINS**

In [74]:
# A LEFT JOIN keeps all of the data from your Left table and whatever matches from the Right table.

# A RIGHT JOIN keeps all of the data from your right table and whatever matches from the Left table. 

# A FULL JOIN brings in everything from both tables and matches whatever will match from the columns you specify. 

# Inner Join in pandas ---- pd.merge(df1, df2, on='id', how = 'inner')

#  Left Join in pandas ---- pd.merge(df1, df2 , on ='id', how = 'left')

# right join in pandas ---- pd.merge(df1, df2, on ='id', how = 'right')

# Full Outer join in pandas --- pd.merge(df1, df2, on = 'id', how = 'outer')

# Join on different column names -- pd.merge(df1, df2, left_on ='user_id, right_on ='id', how ='inner')

# Union all -- pd.concat([df1, df2])

# Union -- pd.concat([df1, df2]).drop_duplicates()